


x-syftet-common-env: &syftet-common-env
  SYFTET_API_BASE_URL: ${SYFTET_API_BASE_URL:-https://syfmart.com/api/v1}
  SYFTET_API_KEY: ${SYFTET_API_KEY:-}
  LOG_LEVEL: info
  AI_PROVIDER: ${AI_PROVIDER:-ollama}
  GROQ_API_KEY: ${GROQ_API_KEY:-your-groq-api-key-here}
  AI_MODEL: ${AI_MODEL:-gemma4:cloud}
  AI_TEMPERATURE: ${AI_TEMPERATURE:-}
  AI_MAX_TOKENS: ${AI_MAX_TOKENS:-}
  AI_TOP_P: ${AI_TOP_P:-}
  OLLAMA_HOST: ${OLLAMA_HOST:-http://192.168.68.107:11434}
  AI_REASONING_EFFORT: ${AI_REASONING_EFFORT:-}




services:
  syftet-mcp:
    build: ./syftet-ecommerce-mcp
    container_name: syftcommerce-mcp
    ports:
      - "4001:4001"
    environment:
      <<: *syftet-common-env
      MCP_PORT: 4001
    restart: unless-stopped

  chat-backend:
    build: ./chat-demo/backend
    container_name: syftcommerce-chat-backend
    ports:
      - "4000:4000"
    environment:
      <<: *syftet-common-env
      PORT: 4000
      MCP_SERVER_URL: http://syftet-mcp:4001
    depends_on:
      - syftet-mcp
    restart: unless-stopped

  chat-frontend:
    build:
      context: ./chat-demo/frontend
      args:
        VITE_API_URL: /api
    container_name: syftcommerce-chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - chat-backend
    restart: unless-stopped
